### ISSUE TITLE
pack - URI encodes filenames

### ISSUE THREAD

**Issue by Andreas-Schommer** [chocolatey/choco#1628]
### What You Are Seeing?
Choco pack encodes filenames different to nuget. Filenames are uri encoded in choco, Nuget leaves them intact.
There was an [issue](https://github.com/NuGet/Home/issues/5726) fixed in nuget addressing the same issue.
The created packages can be installed without problems (with nuget as well as with chocolatey).

I used nuget 4.7.0.5148 and chocolatey v0.10.11 to do the repro.

### What is Expected?
Choco pack and nuget pack should handle filenames alike, filenames with special characters and spaces should be preserviced in the nupkg.

### How Did You Get This To Happen? (Steps to Reproduce)
I created a nuspec file that contains files with special characters and spaces in their names:

  <files>
	<file src="Filename With Spaces.txt" />
	<file src="Filename_With_Umlaute_ÄÖÜäöüß.txt" />
  </files>

I used nuget pack and choco pack to create the package.

When opening the nupkg created with nuget as a ZIP archive,, the filenames are the original filenames used to create the package.
When opening the nupkg created with choco as a ZIP archive, the filenames are URI encoded.

[Repro.zip](https://github.com/chocolatey/choco/files/2285712/Repro.zip)

This issue has been moved over from [chocolatey/chocolatey.org](https://github.com/chocolatey/chocolatey.org/issues/588).

**Comment by bcurran3** [comment]
I'm not an expert on NuGet so I'm not sure if this is relevant, but keep in mind that Chocolatey is based on NuGet v2. (Someone correct me if I'm wrong!)

**Comment by ViceIce** [comment]
Now this is a problem.

If i pack a folder with spaces with NuGet 4.9.2.5706 then chocolatey v0.10.11 will not extract that folder.

Regards
Michael

**Comment by ViceIce** [comment]
I found a workaround.

This does not work:
```xml
<file src="html\**\*.html" target="content/Style Library" />
```

This works:

```xml
<file src="html\**\*.html" target="content/Style%20Library" />
```

**Comment by rgl** [comment]
I'm also affected by this issue. A `choco pack` on a directory that contains file names with white spaces (which unfortunately is common on Unity generated projects, e.g. they normally have a file named `unity default resources`) works; but when you try to `choco install` it, it simply fails without any clue about the problem.

**Comment by TheCakeIsNaOH** [comment]
This was fixed as a part of v2.0.0, as the NuGet libraries were updated. I think this issue can be closed, as the NuGet library tests should cover this fuctionality?

**Comment by corbob** [comment]
@Andreas-Schommer, @viceice, or @rgl, I realize this is a really old issue. Are any of you able to reproduce this issue still?

**Comment by viceice** [comment]
don't know, I no longer have spaces, so it's no longer an issue for me.

**Comment by pauby** [comment]
I'm going to go ahead and close this as stale, but we can reopen it if necessary.
