### ISSUE TITLE
Pass user/pass with source specified 

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#201]
Sources with auth can only be used as part of default sources at the current time.

This means to install from a source with basic auth, you need to add the source to your default sources.

`choco source add -n "name" -s "https://somewhere.outthere.com/api/v2/" -u "username -p "password"`

And then you can just install packages from that source

`choco install custompackage -y`

Specifying source on the command overrides the source information from the default feeds, so trying

`choco install custompackage -y -source "https://somewhere.outthere.com/api/v2"` will not have the user name and password, so it will fail. It would be best to enhance the ability to pass both `-user -password` when also specifying `-source`.

**Comment by brucewilkins** [comment]
When adding the source, I get an error:  

"Unknown command . Setting to list."

**Comment by brucewilkins** [comment]
ok, added the source but still get the original failure when installing:

The package was not found with the source(s) listed.

Is there anyway for me to debug and see whats going on?

**Comment by ferventcoder** [comment]
@brucewilkins how are you calling to install the application? You must not use `-source` at all.

**Comment by ferventcoder** [comment]
And debugging - use `-dv`

**Comment by brucewilkins** [comment]
command: choco install wortell-apps-devenv --force -v -y -dv

**Comment by brucewilkins** [comment]
![choco_exit_1](https://cloud.githubusercontent.com/assets/2183465/6829231/0a35170e-d30a-11e4-8b11-74c34f119de9.png)

**Comment by ferventcoder** [comment]
Kkay, let's file a bug. That is not appropriate behavior if the package exists.

**Comment by brucewilkins** [comment]
Any work around for the time being? Got a bunch of new developers starting and would really like to use choco to get them started.

**Comment by ferventcoder** [comment]
Let's file an issue and I will get you going on 0.9.9.5

**Comment by The1nternet** [comment]
Note, the bug suggests adding the source with the "choco source add" command, but this does not cause the feed to work. After adding the source with its un/pw, I still get 0 results and "unable to find package" errors.

**Comment by ferventcoder** [comment]
This was fixed in 0.9.9.5

**Comment by ctaggart** [comment]
This works great with my AppVeyor NuGet feed! :+1: 
choco update chocolatey -y
choco install --help
![image](https://cloud.githubusercontent.com/assets/80104/7644840/0fa36402-fa60-11e4-8f0c-94069bb0f489.png)

**Comment by amanbansal86** [comment]
I am still facing this issue Chocolatey v0.10.15  The package was not found with the source(s) listed. . even after adding the source .
using jfrog artifactory.  i am providing the username and password . still getting the error package not listed .

**Comment by ferventcoder** [comment]
@amanbansal86 I'm not sure the issue you are mentioning is the same as what was noted here. You may want to file a new issue.
