### ISSUE TITLE
Chocolatey doesn't elevate

### ISSUE THREAD

**Issue by AeliusSaionji** [chocolatey/choco#434]
First- I'm using the proper User / Admin configuration that the Windows userbase tend to scoff at. That is, I use a "User" account, and when I "Run as Admin" UAC runs the executable under an entirely different "Admin" account. This is par for the course in linux, but as I'm sure you're aware most Windows users tend to just create one Administrative account and call it a day.

I bring this up because there's a good chance this is the root of the issue- something is written so that it works in an Administrative account and doesn't actually properly utilize UAC. I don't really know anything about how chocolatey is set up, but I do know that the powershell
`Start-Process $process -Verb Runas`
correctly requests elevation for both User and Admin type accounts.

The problem: chocolatey does not elevate processes for me. Many installers internally request elevation, so the problem appears intermittent, but I'm fairly certain chocolatey consistently fails every time it tries to elevate a process itself. As such, whichever packages in the repo that rely on chocolatey to elevate WILL fail unless I run cinst from an administrative powershell terminal.

**Comment by ferventcoder** [comment]
@Link-Satonaka you've probably had a look through Start-ChocolateyProcessAsAdmin. 

https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Start-ChocolateyProcessAsAdmin.ps1#L66 is the line where it passes `-Verb "runas"`. I think something else may be going on for you somewhere here.

If you wouldn't mind, use `choco install -dv` plus your arguments, then send the entire log of the output along as a gist for further review.

**Comment by ferventcoder** [comment]
> As such, whichever packages in the repo that rely on chocolatey to elevate WILL fail unless I run cinst from an administrative powershell terminal.

Also, if you haven't had a chance, you should read up on why you need to change the default install location - https://github.com/chocolatey/choco/wiki/Installation#non-administrative-install

Note that non-admins can write to that section as well, but they cannot append or modify existing files. We are locking this down further in 0.9.9.9, see #398.

**Comment by Link-Satonaka** [comment]
Noted, thanks.

It's strange, the paint.net installer will request elevation if run, but when passed through Start-ChocolateyProcessAsAdmin, it fails with Exception calling "Start" with "1" argument(s): "The requested operation requires elevation"

**Comment by ferventcoder** [comment]
Do you have a debug log for this one?

**Comment by Link-Satonaka** [comment]
Using this install script http://sprunge.us/MTGd
```powershell
$packageName = 'paint.net'
$fileType = 'EXE'
$silentArgs = '/auto DESKTOPSHORTCUT=0'
$url = '{{DownloadUrl}}'

# Zipped installer
Get-ChocolateyWebFile $packageName "$ENV:Temp\paint.net.install.zip" $url
Get-ChocolateyUnzip "$ENV:Temp\paint.net.install.zip" "$ENV:Temp\pdn"
$installFile = Get-ChildItem -Path "$ENV:Temp\pdn" -Recurse -Include "*.exe" | Select-Object -First 1

# elevation bug
Install-ChocolateyPackage $packageName $fileType $silentArgs $installFile
#Start-Process -FilePath "$installFile" -ArgumentList "$silentArgs" -Verb Runas
```

Dump of the log
http://sprunge.us/eEfR

**Comment by ferventcoder** [comment]
Once you've downloaded the file, you should use `Install-ChocolateyInstallPackage`, not `Install-ChocolateyPackage`

**Comment by ferventcoder** [comment]
I wonder what may have changed with Windows 10 and elevation. Apparently it may not be enough to use RunAS anymore.

**Comment by Link-Satonaka** [comment]
Did not know about `Install-ChocolateyInstallPackage`, but the results do not change. What is the difference, it just doesn't copy the binary to TEMP?

http://sprunge.us/dgXS

**Comment by ferventcoder** [comment]
Right now you are copying the file onto itself. The first is a superset of Get-ChocolateyWebFile and then Install-CHocolateyInstallPackage.

**Comment by Link-Satonaka** [comment]
OK, yeah I noticed it copied the file when using `Install-ChocolateyPackage` and I intentionally extracted it to TEMP\pdn so it would not throw "file exists" errors. Good to know there's a better way, thanks

**Comment by yurikoles** [comment]
I can confirm that choco just fails on non-admin console on win10.

**Comment by iainnicol** [comment]
The problem is that `Start-ChocolateyProcessAsAdmin` sets UseShellExecute to false.  This is required to redirect stderr.  But UseShellExecute must be true for the runas verb (for the UAC prompt) to have any effect. See <https://stackoverflow.com/a/3596354>.

I've seen named pipes mooted as a hairy workaround.  But I have a slightly less hairy workaround. First use `Start-Process -Verb runas` to execute a private, intermediary, script as admin.  The intermediary script then does `Start-Process -RedirectStandardError` and executes the process we're actually trying to execute.

Would it be ok to stick such a private, intermediary, script in the same `src/chocolatey.resources/helpers/functions/` directory as `Start-ChocolateyProcessAsAdmin.ps1`?

**Comment by ferventcoder** [comment]
> Would it be ok to stick such a private, intermediary, script in the same src/chocolatey.resources/helpers/functions/ directory as Start-ChocolateyProcessAsAdmin.ps1?

Probably not. We are working on rewriting these functions into c# cmdlets. We won't have the same issues when we do that (I know this for a fact as that is what shimgen does already).

**Comment by Link-Satonaka** [comment]
Using Win10, no new issues for me since 8.1 with chocolatey, @yurikoles 
In other news, I tried correctly installing chocolatey to a folder outside of programdata and due to this bug almost no packages are install-able :/

**Comment by iainnicol** [comment]
> Probably not. We are working on rewriting these functions into c# cmdlets.

Understandable.

> We won't have the same issues when we do that (I know this for a fact as that is what shimgen does already).

OK, I'm still pretty sure about my diagnosis.  I presume shimgen isn't redirecting stderr?

Here's a minimal testcase.  It doesn't invoke UAC, because UseShellExecute = false to allow RedirectStandardError = true.

```C#
using System.Diagnostics;

namespace StartProcessTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var procInfo = new ProcessStartInfo("notepad");
            procInfo.RedirectStandardError = true;
            procInfo.UseShellExecute = false;

            procInfo.Verb = "runas";

            Process.Start(procInfo);
        }
    }
}
```

**Comment by ferventcoder** [comment]
Actually, it appears that we do switch on UseShellExecute to true, but somehow we are still redirecting StdErr?

**Comment by ferventcoder** [comment]
It's done through EnableRaisingEvents though

**Comment by iainnicol** [comment]
Interesting.  Honestly, I'm a bit confused.  Regardless, I'll leave this for now given the planned rewrite.

@Link-Satonaka, for an **ugly** interim workaround, I suggest you comment out the following lines of `chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1`:
```powershell
$psi.RedirectStandardError = $true # L59
$psi.UseShellExecute = $false # L60
$s.StandardError.ReadToEnd() | Out-File $errorFile # L81
$innerError = Get-Content $errorFile | Out-String # L88
```

**Comment by yurikoles** [comment]
@ferventcoder why don't you use git-flow approach to resolve this issue in stable to don't keep users waiting for rewrite?

**Comment by yurikoles** [comment]
@Link-Satonaka are your Win10 instance is clean install or upgrade? I have a clean install one from 1511 ISO.

**Comment by ferventcoder** [comment]
> why don't you use git-flow approach to resolve this issue in stable to don't keep users waiting for rewrite?

@yurikoles I'm not quite sure what you are referring to. If you are talking about a quick fix and then a permanent fix later, that really doesn't have anything to do with git-flow. And really neither does stable vs master. Git Flow is an approach to development but it doesn't dictate where one should resolve an issue. Most common workflows would do a bug fix in the stable branch.

**Comment by ferventcoder** [comment]
@yurikoles rewrite - Now I understand. We already pushed master to stable in preparation for 0.9.10. If we think this is a big enough issue, I can create a 0.9.9.x branch off of the last tag and move forward there. However I am working on a possible fix right now.

**Comment by ferventcoder** [comment]
Can we determine if this is now fixed with the latest beta? 

https://chocolatey.org/packages/chocolatey/0.9.10-beta-20160111 (note it may not be ready for 1-3 hours while the validator and verifier run).

**Comment by Link-Satonaka** [comment]
Sorry, still not working
https://gist.github.com/Link-Satonaka/40cd66d4e0400d939020

**Comment by ferventcoder** [comment]
Thanks for checking. Dragging out the important parts here - it looks like using `ProcessStartInfo.Verb = RunAs` may no longer work on Windows 10.

~~~
:39:32,713 [DEBUG] - Setting RunAs for elevation
2016-01-11 15:39:32,758 [WARN ] - WARNING: Write-ChocolateyFailure is deprecated. If you are the package maintainer, please use 'throw $_.Exception' instead.
2016-01-11 15:39:32,758 [ERROR] - ERROR: Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"

 at Write-ChocolateyFailure, C:\tools\Chocolatey\helpers\functions\Write-ChocolateyFailure.ps1: line 24
at <ScriptBlock>, C:\tools\Chocolatey\lib\paint.net\tools\chocolateyInstall.ps1: line 12
at <ScriptBlock>, C:\tools\Chocolatey\helpers\chocolateyScriptRunner.ps1: line 48
~~~

**Comment by ferventcoder** [comment]
> But UseShellExecute must be true for the runas verb (for the UAC prompt) to have any effect. See https://stackoverflow.com/a/3596354.

Or as previously stated (https://github.com/chocolatey/choco/issues/434#issuecomment-158792680), using UseShellExecute must be set true.

**Comment by Link-Satonaka** [comment]
I was under Windows 8.1 when I opened this :)

Looking at the comments for this thread http://stackoverflow.com/questions/133379/elevating-process-privilege-programatically

someone mentioned that StartInfo.UseShellExecute must be $true for RunAs to work.

**Comment by Link-Satonaka** [comment]
Beat me to it by 36 seconds

**Comment by ferventcoder** [comment]
Yeah. I think at one time this worked, then we started redirecting output and it stopped working.

**Comment by yurikoles** [comment]
up?

**Comment by lhahne** [comment]
I am getting this with Windows 7. I have a separate user account for admin and I'm trying to run choco as regular user.

```
Installing jdk8...
 DEBUG: Running 'Start-ChocolateyProcessAsAdmin' with
 exeToRun:'C:\ProgramData\chocolatey\lib\jdk8\tools\jdk-8u92-windows-x64.exe', statements: '/s STATIC=1
 ADDLOCAL="ToolsFeature,SourceFeature" '
 DEBUG: Elevating Permissions and running C:\ProgramData\chocolatey\lib\jdk8\tools\jdk-8u92-windows-x64.exe /s STATIC=1

 ADDLOCAL="ToolsFeature,SourceFeature" . This may take a while, depending on the statements.
 Exception calling "Start" with "1" argument(s): "The requested operation requires elevation"
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:76 char:3
 +   $s = [System.Diagnostics.Process]::Start($psi)
 +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
     + FullyQualifiedErrorId : Win32Exception
Command ['"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Comman
d "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICultur
e = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey
\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\jdk8\tools\chocolateyInstall.ps1' -in
stallArguments '' -packageParameters ''"'] exited with '1'
Calling command ['"shutdown" /a']
```

**Comment by ferventcoder** [comment]
@lhahne the workaround right now is to run with admin privileges. We'll get that fixed in an upcoming version.

**Comment by Link-Satonaka** [comment]
As @ferventcoder said, run chocolatey in admin elevated powershell for now. For apps that install to appdata (like chromium), I have gotten away with running powershell/chocolatey as my user to specially handle running `cup chromium`

**Comment by Baemir** [comment]
pleaserino fixerino the bugerino 

it's very annoying to have to run cmd/powershell in admin mode every time

**Comment by ThaJay** [comment]
This is a dealbreaker for me.

I would expect (being a long time Windows user) to just be able to run a choco install command and not have to worry about it. When elevation is needed, Windows will prompt me.

Instead I get this wall of text saying I need to run my terminal as admin. I am very happy to use Windows Terminal nowadays and it has really improved my workflow by a lot. I have all my git bash, wsl and powershell windows neatly in tabs inside one window. It would thus really hurt my workflow to open a new cmd window as admin just to execute choco commands and I'd rather just execute a downloaded installer because of this.

please fix. If you do, that's one step closer to unix for developers and one argument less to ditch Windows for Ubuntu or something.

**Comment by AeliusSaionji** [comment]
Here's a few very basic functions you can add to your powershell profile to maintain a good workflow.

```powershell
Function cupall {
	$env:LOCALAPPDATA = "C:\Users\$env:USERNAME\AppData\Local"
	$env:USERPROFILE = "C:\Users\$env:USERNAME"
	Start-Process -FilePath 'powershell.exe' -ArgumentList 'cup all -y; Read-Host' -Verb RunAs
}

Function cinst {
	param (
		[Parameter(Mandatory = $true)]
		[string]$package
	)
	$env:LOCALAPPDATA = "C:\Users\$env:USERNAME\AppData\Local"
	$env:USERPROFILE = "C:\Users\$env:USERNAME"
	Start-Process -FilePath 'powershell.exe' -ArgumentList "cinst $package; Read-Host" -Verb RunAs
}

Function cuninst {
	param (
		[Parameter(Mandatory = $true)]
		[string]$package
	)
	$env:LOCALAPPDATA = "C:\Users\$env:USERNAME\AppData\Local"
	$env:USERPROFILE = "C:\Users\$env:USERNAME"
	Start-Process -FilePath 'powershell.exe' -ArgumentList "cuninst $package; Read-Host" -Verb RunAs
}
```

**Comment by technic** [comment]
Hey. Is there any updates on this issue?

**Comment by TheBeeBoi** [comment]
Any updates?
It's been around an year.

**Comment by pauby** [comment]
If we are working on an issue we will update the labels, add comments etc. You'd see some activity here.

We're not working on this at the moment. To set expectations, we don't have any plans in the immediate future. It is something we do want to look at and implement, if possible, but have no timescales to share.

**Comment by vexx32** [comment]
Testing this with a simple test-case package which just calls `Install-ChocolateyPath -PathToInstall $path -PathType Machine` (which requires elevation) in Chocolatey v2.2.2, at least in a Vagrant VM environment (which may impact how UAC is configured, I'm not fully sure), this kind of operation where you try to do something that requires elevation as a non-admin user... seems to recursively spawn new PowerShell processes "trying" to elevate the process, but never actually managing to elevate the process properly.

This continues until the machine runs out of memory and Windows seems to sometimes prompt to kill the misbehaving process tree.

As is noted [in our documentation](https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install), the non-admin installation configuration is... not straightforward and we don't _expect_ this kind of thing to work in a lot of cases.

There may be something to be said for the `Start-ChocolateyProcessAsAdmin` command we have being simply not functional for what it's meant to do (anymore?) and we may want to consider reworking some of these code paths to simply throw an error rather than attempt to start an elevated PowerShell process, which we know doesn't actually work.

**Comment by schittli** [comment]
### This is an unbelievable shame ...
### and perhaps it will help the project to understand why potential customers quickly remove Chocolatey from the evaluation:

1. We have 750 employees and wanted to use Chocolatey for deploy - and this 9 year old shame (Issue) is one of the reasons why we didn't choose Choco: the handling is just a nightmare.
2. In 99/100 installations by our employees, we just want to be able to tell them: Run the command `“choco install <packagename>”` - and **everything** else runs automatically.
3. But with Chocolatey, the user receives an incomprehensible message that they have to start the elevated session manually.
4. Of course, we do not want to create a manual or YouTube video, how our employees can use Choco
5. Of course, we also don't want to customize the `choco.exe.manifest` - this “concept” is once again a nightmare because we don't want to maintain this file

### So one of the _most important_ key features for a tool like Chocolatey is:
1. that end users can install SW very easily 
2. and that the tool itself requests the elevated permissions 
3. **if** the package specifies this

So we are curious to see whether Choco will manage to provide this trivial basic function in the next decade - I hope it very much, because Chocolatey has som really great features 😃

**Comment by pauby** [comment]
> 
    We have 750 employees and wanted to use Chocolatey for deploy - and this 9 year old shame (Issue) is one of the reasons why we didn't choose Choco: the handling is just a nightmare.
    In 99/100 installations by our employees, we just want to be able to tell them: Run the command “choco install <packagename>” - and everything else runs automatically.
    But with Chocolatey, the user receives an incomprehensible message that they have to start the elevated session manually.
    Of course, we do not want to create a manual or YouTube video, how our employees can use Choco
    Of course, we also don't want to customize the choco.exe.manifest - this “concept” is once again a nightmare because we don't want to maintain this file

Using Chocolatey for Business, using Chocolatey Agent elevation happens in the background, so the user isn't prompted to do anything. This is not a feature of Chocolatey FOSS.

Are you using Chocolatey for Business?

**Comment by pauby** [comment]
Thanks for raising this issue. After reviewing it, it's not something we expect to prioritise in the foreseeable future. We’re closing it to keep our backlog focused, but we’re open to revisiting it in the future if priorities shift or new interest arises. You are welcome to comment here or open a new issue if you'd like to discuss it further down the line.
