### ISSUE TITLE
choco outdated failing with "error deserializing response"

### ISSUE THREAD

**Issue by elirnm** [chocolatey/choco#790]
### What You Are Seeing?

When 'choco outdated' is run the command fails with 
`"Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Unable to read files snapshot file:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1."`
### How Did You Get This To Happen? (Steps to Reproduce)

This has happened on every run of 'choco outdated' after I installed the Inkscape and GIMP packages.
### Output Log

`Chocolatey is running on Windows v 6.1.7601.65536
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" outdated --debug --verbose
Received arguments: outdated --debug --verbose`

`NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='outdated'|
CacheLocation='C:\Users\frys\AppData\Local\Temp'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|
Sources='https://chocolatey.org/api/v2/'|Debug='True'|Verbose='True'|
Force='False'|Noop='False'|HelpRequested='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|AllVersions='False'|
SkipPackageInstallProvider='False'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='6.1.7601.65536'|
Information.PlatformName='Windows 7'|
Information.ChocolateyVersion='0.9.9.12'|
Information.ChocolateyProductVersion='0.9.9.12'|
Information.FullName='choco, Version=0.9.9.12, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|`

``` Information.Is64Bit='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|
Information.IsProcessElevated='True'|Features.AutoUninstaller='False'|
Features.CheckSumFiles='True'|Features.FailOnAutoUninstaller='False'|
ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
NewCommand.AutomaticPackage='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|FeatureCommand.Command='unknown'|
ConfigCommand.Command='unknown'|PushCommand.TimeoutInSeconds='0'|
PinCommand.Command='unknown'|
_ Chocolatey:ChocolateyOutdatedCommand - Normal Run Mode _
Outdated Packages
 Output is package name | current version | available version | pinned?

7zip 16.02
7zip.install 16.02
ccleaner 5.18.5607
chocolatey 0.9.9.12
ffmpeg 3.0
gimp 2.8.16.20160508
Gow 0.8.0
InkScape 0.91
MobaXTerm 9.0
mpv 2016.04.11.1
mpv.portable 2016.04.11.1
nano 2.5.3
putty 0.67
putty.portable 0.67
qbittorrent 3.3.4
speccy 1.29.714
vcredist2010 10.0.40219.1
vlc 2.2.4
windirstat 1.1.2.20160317
ffmpeg|3.0|3.0.1|false
Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.XmlReader.IsStartElement(String localname, String ns)
   at chocolatey.infrastructure.services.XmlService.<>c__DisplayClass1`1.<deserialize>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.try_catch_with_logging_exception[T](Func`1 function, String err
orMessage, Boolean throwError, Boolean logWarningInsteadOfError)
Unable to read files snapshot file:
 System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.XmlReader.IsStartElement(String localname, String ns)
   at chocolatey.infrastructure.services.XmlService.<>c__DisplayClass1`1.<deserialize>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.try_catch_with_logging_exception[T](Func`1 function, String err
orMessage, Boolean throwError, Boolean logWarningInsteadOfError)
   at chocolatey.infrastructure.services.XmlService.deserialize[XmlType](String xmlFilePath)
   at chocolatey.infrastructure.app.services.ChocolateyPackageInformationService.<>c__DisplayClass2.<get_package_informa
tion>b__1()
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass4.<try_catch_with_logging_exception>b__3()
   at chocolatey.infrastructure.tolerance.FaultTolerance.try_catch_with_logging_exception[T](Func`1 function, String err
orMessage, Boolean throwError, Boolean logWarningInsteadOfError)

Chocolatey has determined 1 package(s) are outdated. .
```

**Comment by ferventcoder** [comment]
This looks like a duplicate of https://github.com/chocolatey/choco/issues/487

**Comment by ferventcoder** [comment]
We've fixed this for 0.9.10, in that we help you determine the file that has the issue and that we wrap these items coming out of the registry a bit better.

**Comment by AAurelianus** [comment]
I deleted all of the .registry files in chocolatey/.chocolatey as advised in #487 but am still getting the error.

**Comment by AAurelianus** [comment]
Following the advice about null characters in https://github.com/chocolatey/choco/issues/487#issuecomment-188672255 I looked in the other files in chocolatey/.chocolatey and found a .files file that was full of null characters. Deleting that solved the issue.

**Comment by ferventcoder** [comment]
Who advised you to delete all of those .registry files? That removes auto uninstaller's ability to automatically uninstall the software those packages represent.

**Comment by ferventcoder** [comment]
Which package was the .files null for?

**Comment by AAurelianus** [comment]
>Who advised you to delete all of those .registry files? 
I thought that's what https://github.com/chocolatey/choco/issues/487#issuecomment-158517457 and https://github.com/chocolatey/choco/issues/487#issuecomment-160163339 were saying to do.

>Which package was the .files null for?
It was [MobaXTerm](https://chocolatey.org/packages/MobaXTerm), though I just forced a reinstall and the new .files file is not corrupt, so it may have been something on my end.

**Comment by ferventcoder** [comment]
The comment said to delete the one file that was causing the issue. Just one file. :)

**Comment by ferventcoder** [comment]
Closing as a duplicate.
